# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\vmware-host\Shared Folders\Documents\BLEIOSAPP\robot\robot.cydsn\robot.cyprj
# Date: Mon, 01 Feb 2016 22:00:56 GMT
#set_units -time ns
create_clock -name {Clock_2(FFB)} -period 50000 -waveform {0 25000} [list [get_pins {ClockBlock/ff_div_7}] [get_pins {ClockBlock/ff_div_8}] [get_pins {ClockBlock/ff_div_9}] [get_pins {ClockBlock/ff_div_10}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/hfclk}] -edges {1 2401 4801} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 45029 90057} -nominal_period 938083.33333333326 [list [get_pins {ClockBlock/udb_div_0}]]


# Component constraints for \\vmware-host\Shared Folders\Documents\BLEIOSAPP\robot\robot.cydsn\TopDesign\TopDesign.cysch
# Project: \\vmware-host\Shared Folders\Documents\BLEIOSAPP\robot\robot.cydsn\robot.cyprj
# Date: Mon, 01 Feb 2016 22:00:52 GMT
